name: Deployment

on:
  release:
    types: 
      - published

jobs:
  build-application:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Delete package-lock.json
      run: rm -f ./package-lock.json

    - name: Install dependencies
      run: npm install

    - name: build application
      run: npm run generate
    
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: .output/public/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-application

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-build
    
    - name: Upload application to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build-artifacts/
